### ISSUE TITLE
`beam` theme's header & footer

### ISSUE THREAD

**Issue by KevinZonda** [rnd195/my-marp-themes#2]
Hello! Thank you for your wonderful work. The themes are really good!

I have a query about the theme beam, its header and footer. I found them in the screenshot, but I tried to apply the theme, but no header, footer and page number apear in the output:

![image](https://github.com/user-attachments/assets/b7518d8e-1fd9-4911-b597-ef3a118be911)

Thank you for your help.

**Comment by KevinZonda** [comment]
Oh sorry, I just realised I didnt config it. Sorry

**Comment by rnd195** [comment]
Hey! Thank you for your kind words. I'm glad that you found the answer.

There's also a sample Marp presentation in the `samples/` folder within this repository ([beam-template.md](https://github.com/rnd195/my-marp-themes/blob/live/samples/beam-template.md)) where you may find some other tricks related to this particular theme.
